# Generated by Django 2.1.5 on 2019-01-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kickstarter',
            fields=[
                ('kickstarter_id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('category', models.CharField(max_length=1024)),
                ('main_category', models.IntegerField()),
                ('currency', models.FloatField()),
                ('deadline', models.CharField(max_length=1024)),
                ('goal', models.CharField(max_length=1024)),
                ('launched', models.CharField(max_length=1024)),
                ('pledged', models.CharField(max_length=1024)),
                ('state', models.CharField(max_length=1024)),
                ('backers', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=1024)),
                ('usd_pledged', models.CharField(max_length=1024)),
                ('usd_pledged_real', models.CharField(max_length=1024)),
                ('usd_goal_real', models.CharField(max_length=1024)),
            ],
        ),
    ]
